### ISSUE TITLE
ava.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference

### ISSUE THREAD

**Issue by tangnuo** [LeeeYou/RsKotlin#2]
09-28 11:51:35.239 28429-28429/com.xyz.leeeyou.zhihuribao E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.xyz.leeeyou.zhihuribao, PID: 28429
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference
                                                                                at com.xyz.leeeyou.zhihuribao.view.fragment.OneFragment.onCreateView(OneFragment.kt:48)
                                                                                at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
                                                                                at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
                                                                                at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                                                                                at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1969)
                                                                                at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:620)
                                                                                at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
                                                                                at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                                at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                                at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                                at android.view.View.measure(View.java:19861)
                                                                                at in.srain.cube.views.ptr.PtrFrameLayout.measureContentView(PtrFrameLayout.java:224)
                                                                                at in.srain.cube.views.ptr.PtrFrameLayout.onMeasure(PtrFrameLayout.java:202)
                                                                                at android.view.View.measure(View.java:19861)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                at android.view.View.measure(View.java:19861)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                at android.view.View.measure(View.java:19861)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                at android.view.View.measure(View.java:19861)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                at android.view.View.measure(View.java:19861)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                at android.view.View.measure(View.java:19861)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                at android.view.View.measure(View.java:19861)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                at com.android.internal.policy.DecorView.onMeasure(DecorView.java:692)
                                                                                at android.view.View.measure(View.java:19861)
                                                                                at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
                                                                                at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
                                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:686)
09-28 11:51:35.239 28429-28429/com.xyz.leeeyou.zhihuribao E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by Jus7inLee** [comment]
我是这样解决的->尝试把出错的这一段代码，放到onActivityCreated里面。（原因->控件还没有初始化成功就 调用setLinearLayoutManager的方法所以就报错了。）

**Comment by LeeeYou** [comment]
已修复，将下面这句放到initAdapter()中
```java
recyclerViewOne?.layoutManager = LinearLayoutManager(context, LinearLayoutManager.VERTICAL, false)
```
